development:
  adapter: mysql
  encoding: utf8
  database: courses_development
  username: root
  password: password
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: courses_development
  username: root
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: courses_production
  pool: 5
  username: masonfoxmatthews
  password:

distyll:
  adapter: mysql
  encoding: utf8
  database: courses_distyll
  username: root
  password: password
  host: localhost
